### ISSUE TITLE
Update command for gke cluster admin role binding

### ISSUE THREAD

**Issue by tariq-islam** [daniel-kun/kube-alive#6]
Should be: 
```
kubectl create clusterrolebinding cluster-admin-binding \
--clusterrole cluster-admin --user $(gcloud config get-value account)
```

Calling the binding `root-cluster-admin-binding` causes the deploy.sh to fail.

*edit: I think the issue was on my end - appears I had run the above command earlier and then created another binding using the command in your README. Still, the above command is cleaner and consistent with GKE docs 👍

**Comment by daniel-kun** [comment]
Thanks! Will test it out as soon as possible and then update the docs.
